apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: rancher-demo
  template:
    spec:
      containers:
      - name: rancher-demo
        image: monachus/rancher-demo:latest
        resources:
          requests:
            cpu: "3m"
            memory: "2Mi"
          limits:
            cpu: "500m"
            memory: "10Mi"
        envFrom:
        - configMapRef:
            name: rancher-demo-config
