apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rancher-demo
  namespace: $(MY_NAMESPACE)
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rancher-demo
  targetCPUUtilizationPercentage: 30
